STOP_WORDS = ['the', 'a', 'an', 'of', 'in', 'to', 'from', 'this', 'that',
              'these', 'those', 'some', 'any', 'on', 'at', 'by', 'with',
              'about', 'against', 'between', 'into', 'through', 'during',
              'before', 'after', 'above', 'below', 'since', 'until', 'under',
              'over', 'again', 'further', 'then', 'once', 'and', 'but', 'or',
              'nor', 'so', 'yet', 'for', 'I', 'you', 'he', 'she', 'it', 'we',
              'they', 'me', 'him', 'her', 'us', 'them', 'my', 'your', 'his',
              'her', 'its', 'our', 'their', 'mine', 'yours', 'theirs', 'is',
              'am', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has',
              'had', 'do', 'does', 'did', 'will', 'would', 'shall', 'should',
              'can', 'could', 'may', 'might', 'must', 'not', 'very', 'just',
              'too', 'now', 'more', 'most', 'less', 'least', 'only', 'even',
              'much', 'up', 'down', 'here', 'there', 'where', 'why', 'how',
              'when']
